name: Run tests

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, labeled]
  schedule:
    - cron: '0 0 * * *'

jobs:
  access_check:
    runs-on: ubuntu-latest
    name: Access check
    steps:
      - name: Ensure pull-request is safe to run
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const repository = context.repo.repo;
            const owner = context.repo.owner;
            
            const response = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo: repository,
              issue_number
            });
            const labels = response.data.map(label => label.name);
            let hasLabel = labels.includes('safe-to-test')
            
            if (context.payload.action === 'synchronize' && hasLabel) {
                hasLabel = false
                await github.rest.issues.removeLabel({
                  owner,
                  repo: repository,
                  issue_number,
                  name: 'safe-to-test'
                });
            }
            
            if (!hasLabel) {
              throw "Action was not authorized. Exiting now."
            }

  php-tests:
    runs-on: ubuntu-latest
    needs: access_check
    strategy:
      matrix:
        payload:
          - { laravel: '10.*', php: '8.3', 'testbench': '8.*'}
          - { laravel: '10.*', php: '8.2', 'testbench': '8.*'}
          - { laravel: '10.*', php: '8.1', 'testbench': '8.*'}
          - { laravel: '9.*', php: '8.3', 'testbench': '7.*'}
          - { laravel: '9.*', php: '8.2', 'testbench': '7.*'}
          - { laravel: '9.*', php: '8.1', 'testbench': '7.*'}
          - { laravel: '9.*', php: '8.0', 'testbench': '7.*'}
          - { laravel: '8.*', php: '8.1', 'testbench': '6.*'}
          - { laravel: '8.*', php: '8.0', 'testbench': '6.*'}
          - { laravel: '8.*', php: '7.4', 'testbench': '6.*'}
          - { laravel: '7.*', php: '8.0', 'testbench': '5.*' }
          - { laravel: '7.*', php: '7.4', 'testbench': '5.*' }
          - { laravel: '6.*', php: '8.0', 'testbench': '4.*' }
          - { laravel: '6.*', php: '7.4', 'testbench': '4.*' }

    name: PHP ${{ matrix.payload.php }} - Laravel ${{ matrix.payload.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.payload.php }}
          extensions: mbstring, dom, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.payload.laravel }}" "orchestra/testbench:${{ matrix.payload.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction
      - name: Execute tests
        run: vendor/bin/phpunit
